### ISSUE TITLE
Install instructions are out of date.

### ISSUE THREAD

**Issue by caneraltinbasak** [brightsign/html-virtual-keyboard#1]
I get this error when I use gulp:

13:43:59] Using gulpfile ~/Downloads/html-virtual-keyboard-master/gulpfile.js
[13:43:59] Starting 'clean'...
[13:43:59] Finished 'clean' after 9.33 ms
[13:43:59] Starting 'useref'...
[13:43:59] Starting 'zip'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error: File not found with singular glob: /home/cal/Downloads/html-virtual-keyboard-master/bower_components/bootstrap/dist/css/bootstrap.min.css (if this was purposeful, use `allowEmpty` option)
    at DestroyableTransform.<anonymous> (/home/cal/Downloads/html-virtual-keyboard-master/node_modules/gulp-useref/index.js:65:32)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at emitOne (events.js:96:13)
    at Pumpify.emit (events.js:188:7)
    at Pumpify.Duplexify._destroy (/home/cal/Downloads/html-virtual-keyboard-master/node_modules/duplexify/index.js:195:15)
    at /home/cal/Downloads/html-virtual-keyboard-master/node_modules/duplexify/index.js:179:10
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by bhastings1019** [comment]
Hi @caneraltinbasak - we are actively updating the example. Once the updates are merged, please let us know if there are continued issues installing the project.
